### ISSUE TITLE
no such column: NEW.last_modified: , while compiling: UPDATE products SET expiredAt = ? WHERE id = ?

### ISSUE THREAD

**Issue by oscarvdl** [capacitor-community/sqlite#104]
**Describe the bug**
When running an UPDATE statement I'm getting a `no such column: NEW.last_modified: , while compiling: UPDATE products SET expiredAt = ? WHERE id = ?` error.

I don't understand where the `NEW.last_modified` column is coming from.

**To Reproduce**

In my Ionic app I'm have the following TypeScript code to update the expiredAt column for my products table.
```javascript
CapacitorSQLite.run({ database: this.dbName, statement: 'UPDATE products SET expiredAt = ? WHERE id = ?', values: ['2022-10-05T14:48:00.000Z', '3e54b235-951b-4617-9479-e0ca10a79012']}).then((value: capSQLiteChanges) => console.log(value));
```
When running this query statement the console.log statement outputs:

```javascript
{
  changes: {
    changes: -1
  },
  message: "Error: runSQL failed: no such column: NEW.last_modified: , while compiling: UPDATE products SET expiredAt = ? WHERE id = ?"
}
```

When debugging the Android build I get to `native_compile(sql);` on line 89 of file `net\sqlcipher\database\SQLiteCompiledSql.java` and on this line an exception is thrown. The stack trace before running this line is:

```java
"CapacitorPlugins@9003" prio=5 tid=0x1ce37 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:89)
	  at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
	  at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:91)
	  at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:41)
	  at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1706)
	  at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:79)
	  at com.getcapacitor.community.database.sqlite.SQLite.Database.prepareSQL(Database.java:377)
	  at com.getcapacitor.community.database.sqlite.SQLite.Database.runSQL(Database.java:350)
	  at com.getcapacitor.community.database.sqlite.CapacitorSQLite.run(CapacitorSQLite.java:481)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
	  at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
	  at com.getcapacitor.Bridge$1.run(Bridge.java:542)
	  at android.os.Handler.handleCallback(Handler.java:914)
	  at android.os.Handler.dispatchMessage(Handler.java:100)
	  at android.os.Looper.loop(Looper.java:224)
	  at android.os.HandlerThread.run(HandlerThread.java:67)
```

The exception is thrown in file `src\main\java\com\getcapacitor\community\database\sqlite\SQLite\Database.java` on
line 359:

```java
net.sqlcipher.database.SQLiteException: no such column: NEW.last_modified: , while compiling: UPDATE products SET expiredAt = ? WHERE id = ?
```

**Expected behavior**
I expect it to successfully process the update query and to get an output like this in my console.log:
```javascript
{
  changes: {
    changes: 1
  }
}
```

**Smartphone:**

- Device: Xiaomi Mi 9T Pro
- OS: Android 10
- Browser: stock browser

**Additional context**
Related npm packages used:
```json
"@capacitor-community/sqlite": "^2.9.14",
"@capacitor/android": "^2.4.6",
"@capacitor/core": "2.4.6",
```

**Comment by jepiqueau** [comment]
@oscarvdl Hi, thanks for using the plugin. Can you provide your database schema and some of the data as you create it

**Comment by oscarvdl** [comment]
@jepiqueau first of all, great plugin and thanks for looking into the issue!

Part of the database scheme is below. I only changed the table and column names to mask and simplify the case.
```javascript
{
  "database": "products-db",
  "version": 1,
  "encrypted": false,
  "mode": "full",
  "tables": [
    {
      "name": "categories",
      "schema": [
        {
          "column": "id",
          "value": "TEXT PRIMARY KEY NOT NULL"
        },
        {
          "column": "name",
          "value": "TEXT NOT NULL"
        },
        {
          "column": "description",
          "value": "TEXT NOT NULL"
        }
      ]
    },
    {
      "name": "products",
      "schema": [
        {
          "column": "id",
          "value": "TEXT PRIMARY KEY NOT NULL"
        },
        {
          "column": "categoryId",
          "value": "TEXT NOT NULL"
        },
        {
          "column": "expiredAt",
          "value": "TEXT"
        },
        {
          "foreignkey": "categoryId",
          "value": "REFERENCES categories(id)"
        }
      ]
    },
...
}
```

Then I call an API and sync the data with these kind of queries:
```javascript
CapacitorSQLite.run({ database: this.dbName, statement: 'INSERT OR IGNORE INTO categories (id, name, description) VALUES (?, ?, ?)', values: [categoryId, categoryName, categoryDescription] });
CapacitorSQLite.run({ database: this.dbName, statement: 'INSERT OR IGNORE INTO products (id, categoryId, expiredAt) VALUES (?, ?, ?)', values: [productId, categoryId, productExpiredAt] });
```
I'm going to change this by adding the values in the values of the database schema but I think that's unrelated.

**Comment by jepiqueau** [comment]
@oscarvdl Look at `https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/ImportExportJson.md`. When using `importToJson` each table should have a field `last_modified` to allow for synchronization,.
so your json object must be:
```
{
  "database": "products104-db",
  "version": 1,
  "encrypted": false,
  "mode": "full",
  "tables": [
    {
      "name": "categories",
      "schema": [
        {
          "column": "id",
          "value": "TEXT PRIMARY KEY NOT NULL"
        },
        {
          "column": "name",
          "value": "TEXT NOT NULL"
        },
        {
          "column": "description",
          "value": "TEXT NOT NULL"
        },
        { 
          "column": "last_modified",
          "value": "INTEGER DEFAULT (strftime('%s', 'now'))" 
        }

      ]
    },
    {
      "name": "products",
      "schema": [
        {
          "column": "id",
          "value": "TEXT PRIMARY KEY NOT NULL"
        },
        {
          "column": "categoryId",
          "value": "TEXT NOT NULL"
        },
        {
          "column": "expiredAt",
          "value": "TEXT"
        },
        { 
          "column": "last_modified",
          "value": "INTEGER DEFAULT (strftime('%s', 'now'))" 
        },
        {
          "foreignkey": "categoryId",
          "value": "REFERENCES categories(id)"
        }
      ]
    },
  ]
}
```
If you do not want to create that field you have to create the database with standard SQLite commands. Hope this clarify.

**Comment by jepiqueau** [comment]
@oscarvdl the test has been implemented in `https://github.com/jepiqueau/angular-sqlite-app-starter/tree/refactor`

**Comment by oscarvdl** [comment]
I missed that part of the documentation and this indeed solves my problem. Thanks!

Could image this `last_modified` field being added by default without explicitly defining it in the table schemas as it's a technical field required for the synchronization and not part of the application logic. But that's a design choice.
