### ISSUE TITLE
Android app crashes when creating connection with wrong secret

### ISSUE THREAD

**Issue by t4tapas** [capacitor-community/sqlite#105]
**Describe the bug**
When I am trying to use method `createConnection` with mode `secret` and passing a wrong secret IOS is throwing an error `{"message":"Open command failed: Failed in openOrCreateDatabase Wrong Secret","result":false}` but in android the app is crashing. 

**To Reproduce**

1. Create a database with mode "no-encryption"
2. Encrypt the database with mode "encryption"
3. Change the secret in GlobalSQLite file
4. Call the createConnection with mode "secret" - no error generated
5. Call method open() on the database - App crashes

**Expected behavior**
Android should through exception as IOS with error message

**Plugin Version :** 2.9.14

**Smartphone:**

- Device: Samsung S8
- OS: Android
- Version: 11

**Android crash log:**

Fatal Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
       at com.getcapacitor.Bridge$1.run(Bridge.java:551)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
       at com.getcapacitor.Bridge$1.run(Bridge.java:542)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)

Caused by net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
       at net.sqlcipher.database.SQLiteCompiledSql.native_compile(SQLiteCompiledSql.java)
       at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:89)
       at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
       at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:91)
       at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
       at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
       at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2016)
       at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1902)
       at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2669)
       at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2599)
       at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1247)
       at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1214)
       at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1304)
       at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1292)
       at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1284)
       at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1329)
       at com.getcapacitor.community.database.sqlite.SQLite.Database.open(Database.java:132)
       at com.getcapacitor.community.database.sqlite.CapacitorSQLite.open(CapacitorSQLite.java:131)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
       at com.getcapacitor.Bridge$1.run(Bridge.java:542)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by jepiqueau** [comment]
@t4tapas Hi, thanks for using the plugin. I will have a look later as i am currently full busy with the migration of the plugin `capacitor-data-storage-sqlite` to @Capacitor3.0.0-rc.0

**Comment by jepiqueau** [comment]
@t4tapas to change the secret when your database has been encrypted with the secret defined in the  GlobalSQLite file
- set the value of newsecret in the  GlobalSQLite file with your new secret
- create a connection `createConnection("YOUR_DB", true, "newsecret", YOUR_VERSION)`
- open the db
- close the  connection
- go back to your app and now change the value of secret in the  GlobalSQLite file  with the value of newsecret
- rebuild the app
- create a connection `createConnection("YOUR_DB", true, "secret", YOUR_VERSION)`
- open the db
- do whatever 
- close the  connection

**Comment by t4tapas** [comment]
@jepiqueau , thanks for your reply. For the above solution, I have to release 2 versions on my app. Currently, I am trying to write code to dynamically select whether to use `secret` or `newsecret`.  The problem with Android is if the app crashes, It's a bad user experience and I can't move forward. So when you have time, please look into this issue so that plugin returns an error message. Thanks!

**Comment by jepiqueau** [comment]
@t4tapas Can you share the code you wrote to select dynamically the `secret` or `newsecret` so i can try to reproduce the issue as if i use the recommended method i could not reproduce the issue. I will have a look at soon as i received it from your side.

**Comment by jepiqueau** [comment]
@t4tapas did you try to update to 3.0.0-beta? if yes do you still have the issue as the error reporting has been  fully rewritten?

**Comment by jepiqueau** [comment]
@t4tapas Test with 2.9.16 it should work tell me if not

**Comment by t4tapas** [comment]
@jepiqueau, it's working fine now. I am getting the error and not crashes. Thank you for taking the time to fix this.
