### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: Run: no such table: main.FareTemplates: , while compiling: INSERT INTO 

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capacitor-community/sqlite#234]
Hi,

Do you know how to declare nullable foreign key here? i.e. `FareTemplates` table is not yet created when I run the below query. But `FareTemplateId` is NULL. This error is due to ` FOREIGN KEY(FareTemplateId) REFERENCES FareTemplates(FareTemplateId)` constraint. Any clue, please? Thanks!

```
async createFare(fare: FareModel): Promise<void> {
    const query = `
          CREATE TABLE IF NOT EXISTS Fares (
            FareId TEXT PRIMARY KEY NOT NULL,
            Amount TEXT NOT NULL,
            Date INTEGER NOT NULL,
            FareTips TEXT NULL,
            PaymentTypeId TEXT NOT NULL,
            FareTemplateId TEXT NULL,
            CreatedDate INTEGER NOT NULL,
            last_modified INTEGER NULL,
            FOREIGN KEY(PaymentTypeId) REFERENCES PaymentTypes(PaymentTypeId),
            FOREIGN KEY(FareTemplateId) REFERENCES FareTemplates(FareTemplateId)
          );`;

    await this.sqliteDbConnection.execute(query);

    const sqlQuery = `INSERT INTO Fares (
      FareId,
      Amount,
      Date,
      FareTips,
      PaymentTypeId,
      FareTemplateId,
      CreatedDate) 
      VALUES (?,?,?,?,?,?,?)`;

    const fareId = Guid.create().toString();

    const sqlValues = [
      fareId,
      fare?.amount,
      fare?.date,
      fare?.fareTips,
      fare?.paymentTypeId,
      fare?.fareTemplateId,
      dayjs().unix(),
    ];

 this.sqliteDbConnection.run(sqlQuery, sqlValues, false);
  }
```

Error

```
core.mjs:6495 ERROR Error: Uncaught (in promise): Error: Run: no such table: main.FareTemplates: , while compiling: INSERT INTO Fares (
      FareId,
      Amount,
      Date,
      FareTips,
      PaymentTypeId,
      FareTemplateId,
      CreatedDate) 
      VALUES (?,?,?,?,?,?,?)
Error: Run: no such table: main.FareTemplates: , while compiling: INSERT INTO Fares (
      FareId,
      Amount,
      Date,
      FareTips,
      PaymentTypeId,
      FareTemplateId,
      CreatedDate) 
      VALUES (?,?,?,?,?,?,?)
    at Object.cap.fromNative (home:414:32)
    at <anonymous>:1:18
    at resolvePromise (zone.js:1255:1)
    at zone.js:1162:1
    at rejected (tslib.es6.js:74:89)
    at ZoneDelegate.invoke (zone.js:400:1)
    at Object.onInvoke (core.mjs:25853:33)
    at ZoneDelegate.invoke (zone.js:399:1)
    at Zone.run (zone.js:160:1)
    at zone.js:1318:1
    at ZoneDelegate.invokeTask (zone.js:434:1)
    at Object.onInvokeTask (core.mjs:25840:33)
```

**Comment by jepiqueau** [comment]
@Sampath-Lokuge the easy answer should be to create the table FareTemplates before to add the data to Fares. Can you try to execute("PRAGMA foreign_keys = OFF;) before entering the data and do a execute(PRAGMA foreign_keys = ON;) after. Now after creating the FaresTemplates you will have to update all the Data of Fares to assign the FareTemplateId which seems a bit stupid to me Would be better to create and fill with data the FareTemplates and PaymentType tables before creating the Fares table

**Comment by Sampath-Lokuge** [comment]
Yes, you're right. I just need to create an empty `FareTemplates ` table first and then execute the above query. That is the easiest and more elegant way. Thanks!

**Comment by jepiqueau** [comment]
@Sampath-Lokuge 👍
