### ISSUE TITLE
Electron path database

### ISSUE THREAD

**Issue by Naerian** [capacitor-community/sqlite#235]
Hi!

I saw that the new version (3.4.1) allows set paths for database file for Electron. Is it possible to indicate that it saves the file in the path of the application (.exe)?

**Comment by jepiqueau** [comment]
@Naerian no it should not. It must save it in the path you gave in the capacitor.config.ts. Did you remove the electron foder from your app  and follow all the procedure described. On which OS are you running?. Can you show me the capacitor.config.ts in the app folder and the one in the electron folder.

**Comment by Naerian** [comment]
No... I would like to know if i can save the database file in the root or installation folder application. 

Capacitor.config.ts allow set path for save it (with 3.4.1 version), but I dont know how save the DB file in the installation folder application.

**Comment by Naerian** [comment]
Ohh, ok. Thanks u!!

I have another question: When I run AppImage in Linux, database is created in the same place when app is running... And if I run app from linux-unpacked folder, database is created in the same folder... But I have specified another path in the "capacitor.config.ts" file, like this:

> plugins: {
    CapacitorSQLite:
    {
      iosDatabaseLocation: 'Library/Databases',
      electronWindowsLocation: 'C:\\ProgramData\\Databases',
      electronMacLocation: '/Users/Shared/Databases',
      electronLinuxLocation: '/home/Databases'
    }
  },

In Windows work perfectly, saving database in "C:\ProgramData\Databases", but not on Linux.

**Comment by jepiqueau** [comment]
@Naerian i did not test on Linux as i do not have it installed. So where the databases are created? I am away for 5 days so i will have a look end of next week

**Comment by Naerian** [comment]
Hi @jepiqueau, dabatases, on Linux, are created in the same folder where the executable is located, even though I have set another path in the config file "capacitor.config.ts", like my last answer.

**Comment by jepiqueau** [comment]
@Naerian thanks for this i will review all again end of next week

**Comment by jepiqueau** [comment]
@Naerian can you give me the result of node os.types() under Linux

**Comment by Naerian** [comment]
How can I check node os.types()?

**Comment by jepiqueau** [comment]
@jepiqueau on Linux command Window type node  and on the node prompt type os.type() and send me the result

**Comment by jepiqueau** [comment]
@Naerian on Linux command Window type node and then on the node prompt 
Const os = require('os')
Const type =os.type()
Send me the result of type

**Comment by Naerian** [comment]
I ran my app with electron on Linux from Terminal and y get this error:

> Error: in getDBPath Error: EACCES: permission denied, mkdir '/home/AVDatabases'
    at Object.mkdirSync (fs.js:987:3)
    at UtilsFile._mkdirSyncRecursive (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2570:31)
    at UtilsFile._createFolderIfNotExists (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2549:22)
    at UtilsFile.getDatabasesPath (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2259:27)
    at UtilsFile.getFilePath (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2240:36)
    at new Database (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2924:36)
    at CapacitorSQLite.createConnection (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:3476:25)
    at /home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/electron/dist/core/index.js:1:2583
    at electron/js2c/browser_init.js:197:579
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9782) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/home/AVDatabases'
}
called ipcMain.handle: CapacitorSQLite-isDatabase
Error: in getDBPath Error: EACCES: permission denied, mkdir '/home/AVDatabases'
    at Object.mkdirSync (fs.js:987:3)
    at UtilsFile._mkdirSyncRecursive (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2570:31)
    at UtilsFile._createFolderIfNotExists (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2549:22)
    at UtilsFile.getDatabasesPath (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2259:27)
    at UtilsFile.getFilePath (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2240:36)
    at UtilsFile.isFileExists (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2228:31)
    at CapacitorSQLite.isDatabase (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:3761:38)
    at /home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/electron/dist/core/index.js:1:2583
    at electron/js2c/browser_init.js:197:579
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9782) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/home/AVDatabases'
}

It seems that /home folder doesn't permissions if its not inside the user folder...

OS for tests: Ubuntu 16.04

**Comment by jepiqueau** [comment]
@Naerian can you try a folder under your user

**Comment by Naerian** [comment]
Under my user work...  but the idea its that you don't know user name folder. I tried use "$HOME/Databases" in  "capacitor.config.ts" file, but folder is created in the same executable location.

**Comment by jepiqueau** [comment]
@Naerian it depends if you want to use it only for you or if you want to share the databases in between user of the same  machine. Do you know what is the sharable device on Linux

**Comment by Naerian** [comment]
This is for generate a distributable application for my company. This app will be used for multiples users in differents machines, so I never know what user is using app

**Comment by jepiqueau** [comment]
@Naerian can you try /usr/share/CapacitorDatabases

**Comment by jepiqueau** [comment]
@Naerian you may also try /srv/CapacitorDatabases

**Comment by jepiqueau** [comment]
@Naerian if you give the permission read/White to the /home folder it may work also

**Comment by Naerian** [comment]
With /usr/share folde... same error:

> Error: in getDBPath Error: EACCES: permission denied, mkdir '/usr/share/AVDatabase'
    at Object.mkdirSync (fs.js:987:3)
    at UtilsFile._mkdirSyncRecursive (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2570:31)
    at UtilsFile._createFolderIfNotExists (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2549:22)
    at UtilsFile.getDatabasesPath (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2259:27)
    at UtilsFile.getFilePath (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2240:36)
    at new Database (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2924:36)
    at CapacitorSQLite.createConnection (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:3476:25)
    at /home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/electron/dist/core/index.js:1:2583
    at electron/js2c/browser_init.js:197:579
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9782) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/share/AVDatabase'
}
called ipcMain.handle: CapacitorSQLite-isDatabase
Error: in getDBPath Error: EACCES: permission denied, mkdir '/usr/share/AVDatabase'
    at Object.mkdirSync (fs.js:987:3)
    at UtilsFile._mkdirSyncRecursive (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2570:31)
    at UtilsFile._createFolderIfNotExists (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2549:22)
    at UtilsFile.getDatabasesPath (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2259:27)
    at UtilsFile.getFilePath (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2240:36)
    at UtilsFile.isFileExists (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:2228:31)
    at CapacitorSQLite.isDatabase (/home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:3761:38)
    at /home/santillana/Desktop/linux-unpacked/resources/app.asar/node_modules/@capacitor-community/electron/dist/core/index.js:1:2583
    at electron/js2c/browser_init.js:197:579
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9782) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/share/AVDatabase'
}

I can't give r/w permissions to the "home" folder cuz I said, this app will be use in machines when I don't have access...

I guess you "mkdir" for create folder on Linux. It would be great to be able to set paths like "$HOME/Databases" for Linux (and its respective for Windows), but like I said in my previous aswer, with that path the folder is created in the executable location, cuz I guess this paths is not recognized by the internal command used, in the SQLITE library, for that.

**Comment by jepiqueau** [comment]
@Naerian on each machine the user will use its on databases not share with others can you confirm. If yes put only in the path AVDatabases without any / and it will be created at the user home folder

**Comment by Naerian** [comment]
Hi @jepiqueau! If I set path like "AVDatabases", without "/", the file its created at the user home folder perfectly!

**Comment by jepiqueau** [comment]
@Naerian sorry i thought i had mentioned this in the readme but after checking, it is not but it is effectively the way to have it in the user home. I will have to update the doc. Thanks for this and for your patience. Good luck with your app.

**Comment by jepiqueau** [comment]
@Naerian i did update the readme.md again sorry for all this time wasted

**Comment by Naerian** [comment]
Thx u for you u time!!
