### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by tobiasmuecksch** [capacitor-community/sqlite#257]
In this issue, I want to collect topics and improvements for the documentation.

- Simplified getting started with platform specific hints
- Simplified ["Singleton service"](https://github.com/capacitor-community/sqlite/blob/master/docs/Ionic-Angular-Usage.md) with better readability
- Platform specific quirks and hints
    - e.g. on `electron` we have to call `saveToStore` programmatically. `closeConnection` also does `saveToStore`
- What is the difference between `run`, `query`, `execute` and `executeSet`?
- Detailed information on connection management

Maybe we could implement some documentation website with a framework like https://github.com/facebook/docusaurus

**Comment by tobiasmuecksch** [comment]
Issues to consider for information gathering:

- https://github.com/capacitor-community/sqlite/issues/255
- https://github.com/capacitor-community/sqlite/issues/254
- https://github.com/capacitor-community/sqlite/issues/247
- https://github.com/capacitor-community/sqlite/issues/244
- https://github.com/capacitor-community/sqlite/issues/242
- https://github.com/capacitor-community/sqlite/issues/241

**Comment by tobiasmuecksch** [comment]
@jepiqueau Could you give me some explanation for this question?

> "What is the difference between `run`, `query`, `execute` and `executeSet`?"

**Comment by jepiqueau** [comment]
@tobiasmuecksch 
Query is for select statement
Execute is for executing  a set of raw statement given in a string.
Run is for executing one raw statement Insert, Update, Delete with given values meaning that you prépare the statement and bind the values if any
ExecuteSet is to run on or more raw statements and bind them with values or an array of values .
Hope this clarify

**Comment by jepiqueau** [comment]
@tobiasmuecksch on Electron you do not need to use saveToStore. This is only for the Web platform

**Comment by tobiasmuecksch** [comment]
> @tobiasmuecksch on Electron you do not need to use saveToStore. This is only for the Web platform

My bad. I fixed the issue description.

**Comment by jepiqueau** [comment]
@tobiasmuecksch i just issue a new Ionic/Angular  app demonstrating how to use the @capacitor-community/sqlite plugin to synchronize with a remote server database by using the import & export of Json Object. The deleted rows are now well managed. Look at [angular-sqlite-synchronize-app](https://github.com/jepiqueau/angular-sqlite-synchronize-app), hope this will clarify

**Comment by rakibul111** [comment]
@jepiqueau can you please guide me how can I use this sqlite plugin with nextjs-ionic setup.

**Comment by jepiqueau** [comment]
@rakibul111 exactely the same way that for react, vue, solidjs or angular.

**Comment by jepiqueau** [comment]
@rakibul111 
Npm i -- save @capacitor/core
Npm i --save-dev @capacitor/cli
Npm i --save @capacitor/ios and Android
Npx cap init yourappname yourappid
Npm run build
Npx cap add ios
Npx cap add android
Npx cap sync
Npm run build
Npx cap copy
Npx cap open ios 
Npx cap open android
Thatis it

**Comment by rakibul111** [comment]
@jepiqueau where to setup for jeep-sqlite?

**Comment by rakibul111** [comment]
@jepiqueau Uncaught (in promise) RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): Import #33 module="a" function="I" error: function import requires a callable). Build with -s ASSERTIONS=1 for more info.
    at L (jeep-sqlite.entry.js:2591:71)
    at jeep-sqlite.entry.js:2641:387

**Comment by tobiasmuecksch** [comment]
This is not the right issue for this discussion.
Please open a new issue for that.

**Comment by jepiqueau** [comment]
@rakibul111 as mentioned by @tobiasmuecksch this is not the right place. Any how delete the sql-wasm.wasm file from your assets folder and copy the one from the node_modules/sql.js/dist/sql_wasm.wasm to your asset folder this should solve the issue

**Comment by hannaseithe** [comment]
Just want to reinforce the need for documentation improvements. Spend a while now trying to figure out what was up when I got the error message 'The jeep-sqlite element is not present in the DOM!' in the browser. Would be very helpful to have a more explicit documentation that explains the methods needed (initWebStore and saveToStore) for web support.

**Comment by jepiqueau** [comment]
@jhuenges thanks for your question showing à n interest in the plugin i will answer to those questions and you will be free to create a PR for this as i am quite busy by the maintenance and new features implementation

**Comment by jhuenges** [comment]
I did some research and with my limited knowledge I came to the conclusion that:

## What happens if the user deletes the app?
- **Is the encryption secret kept?**
  - iOS: Yes, since it is stored in the KeyChain
  - Android: No, since everything in the KeyStore related to the app is deleted if the app is deleted
- **Are the databases and tables kept?**
  - They are deleted (?)
- **If the users re-installs the app, can they continue were they left off?**
  - No
- **Are there differences between iOS and Android how this is done?**
  - Yes, see above
  
## Were is the database stored on the phone?
- **Were is the database stored on the phone?**
  - ?
- **Is it included in the backup?**
  - Depending on where it is stored, it can be included or excluded
  
Disclaimer: This is my first adventure into Swift and Java and the iOS and Android ecosystem. So I have little confidence in what I gathered. Any confirmation or correction is greatly appreciated!

**Comment by mburger81** [comment]
@jepiqueau first of all thx you for this great plugin,

I would like to make a question to you, we need to use the plugin with native encryption. For me it's not clear, even because I don't find the informations on the documentation how is the best practice to encrypt the database.

In the documentation I can see the capacitor configuration parameters, like `iosIsEncryption` and `androidIsEncryption`, so i think this is the point where we should decide if a database is encrypted or not?

But at the other way, I see in the `createConnection` command two parameters, `encrypted` and `mode`. 

So my first question is, how matters the `encrypted` parameter of the `createConnection` command with the `iosIsEncryption` parameters from the capacitor configuration?

And my second question is, Im not really sure how to use the `mode` parameter. Do I have to switch this mode between the first DB open and the second DB open? Is it possible to show a best practice workflow to use your plugin with sqlite encrypted?

thx a lot

**Comment by jepiqueau** [comment]
@mburger81  A documentation has been added [DatabaseEncryption](https://github.com/capacitor-community/sqlite/blob/master/docs/DatabaseEncryption.md). Hope this will help you to understand the workflow

**Comment by mmouterde** [comment]
I'm just starting with this sqlite plugin, I hope this will be relevant.

My point is about the _IncrementalUpgrade_ feature documentation.
- The main readme.me show a broken link
- the page [IncrementalUpgradeDatabaseVersion](https://github.com/capacitor-community/sqlite/blob/master/docs/IncrementalUpgradeDatabaseVersion.md) is really clear about the proposal, but less about the final implementation. Is there an example somewhere else ?
- The page [UpgradeDatabaseVersion](https://github.com/capacitor-community/sqlite/blob/master/docs/UpgradeDatabaseVersion.md) seems more relative to the implementation... but mentions an `openDB` function I can't found

During my tests on web platform my `addUpgradeStatement` does not throw error, but has no effect ?! As well as with an empty database as with an existing version.

**Comment by jepiqueau** [comment]
@mmouterde look at ionic7-angular-sqlite-app and at the blog tutorials-app at https://github.com/jepiqueau

**Comment by mmouterde** [comment]
This tuto is not really easy to follow as the final workflow is split into several services. 
Anyway, that a great, complete and verbose work that helps me. thanks @jepiqueau !

If it could help someone, Here is my working resulting version in a single file `src/services/databaseService`.
`databaseService.init()` is simply called from `App.vue`.

Tested with Quasar+vue3+vite+capacitor (web+android)

```js
import { Platform } from 'quasar';
import { CapacitorSQLite, SQLiteConnection, SQLiteDBConnection } from '@capacitor-community/sqlite';
import { version1 } from 'src/migrations/version1';
import { JeepSqlite } from 'jeep-sqlite/dist/components/jeep-sqlite';

const DATABASE_NAME = 'db_name'
const DATABASE_CURRENT_VERSION = 1;

const sqlite: SQLiteConnection = new SQLiteConnection(CapacitorSQLite);

export async function init() {
    customElements.define('jeep-sqlite', JeepSqlite);
    window.addEventListener('DOMContentLoaded', async () => {
        try {
            if (!Platform.is.capacitor) {
                const jeepSqlite = document.createElement('jeep-sqlite');
                document.body.appendChild(jeepSqlite);
                await customElements.whenDefined('jeep-sqlite');
                await sqlite.initWebStore();
            }

            await CapacitorSQLite.addUpgradeStatement({ database: DATABASE_NAME, upgrade: [version1] });

            const ret = await sqlite.checkConnectionsConsistency();
            const isConn = (await sqlite.isConnection(DATABASE_NAME, false)).result;
            let db: SQLiteDBConnection;
            if (ret.result && isConn) {
                db = await sqlite.retrieveConnection(DATABASE_NAME, false);
            } else {
                db = await sqlite.createConnection(
                    DATABASE_NAME,
                    false,
                    'no-encryption',
                    DATABASE_CURRENT_VERSION,
                    false,
                );
            }
            await db.open();
        } catch (err) {
            console.log(`Error: ${err}`);
            throw new Error(`Error: ${err}`);
        }
    });
}
```


```jsx
<template>
    <q-layout>
        <router-view />
    </q-layout>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { init } from 'src/services/databaseService';
export default defineComponent({ name: 'App'});
init();
</script>

```

To going back to the goal of this issue, I guess IncrementalUpgrade part is still confusing as :
-  `openDB` function does not exists.
- "It has to be called prior to open the database with the new version number" => not only prior to open but also even prior `checkConnectionsConsistency`
- According to my recent experience the Vue Usage part as described [here](https://github.com/capacitor-community/sqlite/blob/master/docs/Ionic-Vue-Usage.md#vue-sqlite-hook-declaration-for-platforms-including-web) is not working. According to @jepiqueau tutorial, `jeep-sqlite/loader` seems not relevant any more ?!

**Comment by jepiqueau** [comment]
@mmouterde Sorry the documentation has not been updated. i focus my attention in providing tutorials. look at [link to tuorials](https://jepiqueau.github.io/) and specifically for vue3 at [Vue3-Web](https://github.com/jepiqueau/blog-tutorials-apps/tree/main/SQLite/Part-1/ionic7-vue-sqlite-app) and [Vue3-Native](https://github.com/jepiqueau/blog-tutorials-apps/tree/main/SQLite/Part-2/ionic7-vue-sqlite-app). These tutorials are based on the latest version of Ionic7 and are using Vue with Vite. The upgrade statement must be defined prior to any connection to the database and are read and implemented when you make the connection to the database with the desired version number. This should help you to start.

**Comment by jepiqueau** [comment]
@mmouterde What is important is to define the service as unique throughout your application and i do not know how to do that with Quasar as the App.Vue i s something like this
```html
<template>
  <router-view />
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { Capacitor } from '@capacitor/core';
import { JeepSqlite } from 'jeep-sqlite/dist/components/jeep-sqlite';

export default defineComponent({
  name: 'App',
});
</script>
```
so if i define a setup method i cannot use this.

**Comment by mmouterde** [comment]
Hum, ok, in this case it would be better to use `boot files` hook from Quasar.
from `src/boot/sqlite.ts`
```js
import { boot } from 'quasar/wrappers';
import { init } from 'src/services/databaseService';

export default boot(() => {
    return init();
});

```
And then configure boot scripts option in `quasar.config.js` :
```js
   boot: ['i18n', 'axios', 'sqlite' /*<=*/ ],
```

According to my tests, the `DOMContentLoaded` event has already occurred when boot scripts run. I had to remove the `window.addEventListener('DOMContentLoaded',...) ` from my previous `init()` implementation :

```ts
import { Platform } from 'quasar';
import { CapacitorSQLite, SQLiteConnection, SQLiteDBConnection } from '@capacitor-community/sqlite';
import { version1 } from 'src/migrations/version1';
import { JeepSqlite } from 'jeep-sqlite/dist/components/jeep-sqlite';

const DATABASE_NAME = 'db_name'
const DATABASE_CURRENT_VERSION = 1;

const sqlite: SQLiteConnection = new SQLiteConnection(CapacitorSQLite);

export async function init() {
        customElements.define('jeep-sqlite', JeepSqlite);
        try {
            if (!Platform.is.capacitor) {
                const jeepSqlite = document.createElement('jeep-sqlite');
                document.body.appendChild(jeepSqlite);
                await customElements.whenDefined('jeep-sqlite');
                await sqlite.initWebStore();
            }

            await CapacitorSQLite.addUpgradeStatement({ database: DATABASE_NAME, upgrade: [version1] });

            const ret = await sqlite.checkConnectionsConsistency();
            const isConn = (await sqlite.isConnection(DATABASE_NAME, false)).result;
            let db: SQLiteDBConnection;
            if (ret.result && isConn) {
                db = await sqlite.retrieveConnection(DATABASE_NAME, false);
            } else {
                db = await sqlite.createConnection(
                    DATABASE_NAME,
                    false,
                    'no-encryption',
                    DATABASE_CURRENT_VERSION,
                    false,
                );
            }
            await db.open();
        } catch (err) {
            console.log(`Error: ${err}`);
            throw new Error(`Error: ${err}`);
        }
}
```

**Comment by jepiqueau** [comment]
@mmouterde  In fact i did this and it works
```html
<template>
  <router-view />
</template>

<script lang="ts">
import { defineComponent, createApp, onMounted } from 'vue';
import { Capacitor } from '@capacitor/core';
import { JeepSqlite } from 'jeep-sqlite/dist/components/jeep-sqlite';
import SqliteService from './services/sqliteService';
import DbVersionService from './services/dbVersionService';
import StorageService from './services/storageService';
import InitializeAppService from './services/initializeAppService';

export default defineComponent({
  name: 'App',
  setup() {
    customElements.define('jeep-sqlite', JeepSqlite);
    const app = createApp({});
    const platform = Capacitor.getPlatform();
    // Set the platform as global properties on the app
    app.config.globalProperties.$platform = platform;
    console.log('platform', app.config.globalProperties.$platform);
    // Define and instantiate the required services
    const sqliteServ = new SqliteService();
    const dbVersionServ = new DbVersionService();
    const storageServ = new StorageService(sqliteServ, dbVersionServ);
    // Set the services as global properties on the app
    app.config.globalProperties.$sqliteServ = sqliteServ;
    app.config.globalProperties.$dbVersionServ = dbVersionServ;
    app.config.globalProperties.$storageServ = storageServ;
    //Define and instantiate the InitializeAppService
    const initAppServ = new InitializeAppService(sqliteServ, storageServ);

    const initApp = async () => {
      try {
        await initAppServ.initializeApp();
      } catch (error) {
        console.error('App Initialization error:', error);
      }
    };
    onMounted(async () => {
      if (platform != 'web') {
        await initApp();
      } else {
        window.addEventListener('DOMContentLoaded', async () => {
          const jeepEl = document.createElement('jeep-sqlite');
          document.body.appendChild(jeepEl);
          customElements
            .whenDefined('jeep-sqlite')
            .then(async () => {
              await initApp();
            })
            .catch((err) => {
              console.error('jeep-sqlite creation error:', err);
            });
        });
      }
    });
    return {};
  },
});
</script>
```
the services are the same than in [ionic7-vue-sqlite-app](https://github.com/jepiqueau/blog-tutorials-apps/tree/main/SQLite/Part-1/ionic7-vue-sqlite-app), the models and the upgrades are also the same

**Comment by jepiqueau** [comment]
@mmouterde you can remove the line 
```window.addEventListener('DOMContentLoaded', async () => {```as it is done in the onMounted method it is working too

**Comment by jepiqueau** [comment]
@mmouterde  look at [quasar-sqlite-app](https://github.com/jepiqueau/blog-tutorials-apps/tree/main/SQLite/Part-1/quasar-sqlite-app),  For now only the web part is in the tutorial the native part will come next . Hope this will help you

**Comment by jepiqueau** [comment]
@tobiasmuecksch and all coming to that issue on documentation

To all, I know that the documentation is not up-to-date and part of it will be removed soon as it is difficult to maintain as Capacitor, the plugin and the Frameworks are continuously updated. 
So i will advise you to visit [tutorials](https://jepiqueau.github.io/) which are all compatible with Capacitor 5, Ionic 7 and @capacitor-community/sqlite@5.4.x. If some of you want to see others features, feel free to mention them or to participate in that effort, by creating new tutorials.
