### ISSUE TITLE
Bug: Unable to insert multiple records at once (Bulk insertion)

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capacitor-community/sqlite#264]
Hi,

I need to add bulk records at once. I have tried it like so:

```
createExpenseTemplates(expenseTemplates: ExpenseTemplateModel[]): Promise<capSQLiteChanges> {
    const sqlQuery = `INSERT INTO ExpenseTemplates (
      ExpenseTemplateId,
      TemplateName,
      ExpenseTemplateIconId,
      IsNameEnabled,
      IsAmountEnabled,
      IsDateEnabled,
      IsExpenseTypeEnabled,
      IsVatEnabled,
      IsPhotoEnabled,
      CreatedDate,
      UserId) 
      VALUES (?,?,?,?,?,?,?,?,?,?,?)`;

    const expenseTemplateList: any = [];

    forEach(expenseTemplates, (e) => {
      expenseTemplateList.push([
        e?.id,
        e?.templateName,
        e?.expenseTemplateIconId,
        e?.isNameEnabled,
        e?.isAmountEnabled,
        e?.isDateEnabled,
        e?.isExpenseTypeEnabled,
        e?.isVatEnabled,
        e?.isPhotoEnabled,
        e?.createdDate,
      ]);
    });

    const sqlValues = [expenseTemplateList];

    return this.sqliteDbConnection.run(sqlQuery, sqlValues, false);
  }
```

But it gives exception like so:

```
core.mjs:6495 ERROR Error: Uncaught (in promise): Error: Run: Cannot bind [["cca4a94c-3957-552f-90bd-6c7077aa7a44","tmp","152f86c0-39de-4094-8001-6227bbcc0393",true,true,true,true,true,true,1650178438],["d4fcb17d-cb1f-c2aa-4bbc-e2143ee364c1","expt4","8919c329-aa5c-4630-b2b3-32345c4753b9",true,true,true,true,true,true,1650176901],["0e90e7c6-88fa-da90-db4d-f935d399cfb7","extmp3","8919c329-aa5c-4630-b2b3-32345c4753b9",true,true,true,false,true,true,1650173777],["9c5b0b2f-1754-c706-882a-21fbf7d524a4","exp tmp1","8919c329-aa5c-4630-b2b3-32345c4753b9",true,true,true,true,true,true,1650091148]] at index 1 Supported types: null, byte[], float, double, long, int, short, byte, string
Error: Run: Cannot bind [["cca4a94c-3957-552f-90bd-6c7077aa7a44","tmp","152f86c0-39de-4094-8001-6227bbcc0393",true,true,true,true,true,true,1650178438],["d4fcb17d-cb1f-c2aa-4bbc-e2143ee364c1","expt4","8919c329-aa5c-4630-b2b3-32345c4753b9",true,true,true,true,true,true,1650176901],["0e90e7c6-88fa-da90-db4d-f935d399cfb7","extmp3","8919c329-aa5c-4630-b2b3-32345c4753b9",true,true,true,false,true,true,1650173777],["9c5b0b2f-1754-c706-882a-21fbf7d524a4","exp tmp1","8919c329-aa5c-4630-b2b3-32345c4753b9",true,true,true,true,true,true,1650091148]] at index 1 Supported types: null, byte[], float, double, long, int, short, byte, string
    at Object.cap.fromNative (VM3:414:32)
    at <anonymous>:1:18
    at resolvePromise (zone.js:1255:1)
    at zone.js:1162:1
    at rejected (tslib.es6.js:74:89)
    at ZoneDelegate.invoke (zone.js:400:1)
    at Object.onInvoke (core.mjs:25853:33)
    at ZoneDelegate.invoke (zone.js:399:1)
    at Zone.run (zone.js:160:1)
    at zone.js:1318:1
    at ZoneDelegate.invokeTask (zone.js:434:1)
    at Object.onInvokeTask (core.mjs:25840:33)
```

This is Ionic/Angulat native app. Please let me know what is the issue here. Thanks!

**Comment by tobiasmuecksch** [comment]
@Sampath-Lokuge You are using it wrong. The correct implementation would look more like this:

```typescript
async createExpenseTemplates(expenseTemplates: ExpenseTemplateModel[]): Promise<capSQLiteChanges[]> {
    const sqlQuery = `INSERT INTO ExpenseTemplates (
      ExpenseTemplateId,
      TemplateName,
      ExpenseTemplateIconId,
      IsNameEnabled,
      IsAmountEnabled,
      IsDateEnabled,
      IsExpenseTypeEnabled,
      IsVatEnabled,
      IsPhotoEnabled,
      CreatedDate,
      UserId) 
      VALUES (?,?,?,?,?,?,?,?,?,?,?)`;

   const results: capSQLiteChanges[] = [];

    for (const expenseTemplate of expenseTemplates) {
       const values = [
        e?.id,
        e?.templateName,
        e?.expenseTemplateIconId,
        e?.isNameEnabled,
        e?.isAmountEnabled,
        e?.isDateEnabled,
        e?.isExpenseTypeEnabled,
        e?.isVatEnabled,
        e?.isPhotoEnabled,
        e?.createdDate,
      ];

      const currentResult = await this.sqliteDbConnection.run(sqlQuery, values, false);

     results.push(currentResult);
   }

    return results;
  }
```

**Comment by Sampath-Lokuge** [comment]
Hi,

I have tried like so. But it is not working. Please let me know this issue here.

```
createExpenseTemplates(expenseTemplates: ExpenseTemplateModel[]): Promise<capSQLiteChanges> {
    const statement = `INSERT INTO ExpenseTemplates (
      ExpenseTemplateId,
      TemplateName,
      ExpenseTemplateIconId,
      IsNameEnabled,
      IsAmountEnabled,
      IsDateEnabled,
      IsExpenseTypeEnabled,
      IsVatEnabled,
      IsPhotoEnabled,
      CreatedDate,
      UserId) 
      VALUES (?,?,?,?,?,?,?,?,?,?,?)`;

    const sqlValues: any = [];

    forEach(expenseTemplates, (e) => {
      sqlValues.push([
        e?.id,
        e?.templateName,
        e?.expenseTemplateIconId,
        e?.isNameEnabled,
        e?.isAmountEnabled,
        e?.isDateEnabled,
        e?.isExpenseTypeEnabled,
        e?.isVatEnabled,
        e?.isPhotoEnabled,
        e?.createdDate,
        e?.userId,
      ]);
    });


    const results: capSQLiteSet[] = [
      {
        statement,
        values: [sqlValues],
      },
    ];

 

    return this.sqliteDbConnection.executeSet(results, true);
  }
```

![1](https://user-images.githubusercontent.com/5206526/164417707-33d38074-c730-4621-8e49-b2467c0da59a.png)


![2](https://user-images.githubusercontent.com/5206526/164417735-b4e2d97a-6e2d-45ae-81f3-3db30131c633.png)


![3](https://user-images.githubusercontent.com/5206526/164417759-f32a2998-b40c-4d31-a5f5-aef263048405.png)

**Comment by tobiasmuecksch** [comment]
The issue is, that you are still using it wrong. Please have a close look at the documentation for [`executeSet()`](https://github.com/capacitor-community/sqlite/blob/master/docs/APIDBConnection.md#executeset) and [`capSQLiteSet`](https://github.com/capacitor-community/sqlite/blob/master/docs/APIDBConnection.md#capsqliteset).

It should work like this:

```typescript

createExpenseTemplates(expenseTemplates: ExpenseTemplateModel[]): Promise<capSQLiteChanges> {
    const statement = `INSERT INTO ExpenseTemplates (
      ExpenseTemplateId,
      TemplateName,
      ExpenseTemplateIconId,
      IsNameEnabled,
      IsAmountEnabled,
      IsDateEnabled,
      IsExpenseTypeEnabled,
      IsVatEnabled,
      IsPhotoEnabled,
      CreatedDate,
      UserId) 
      VALUES (?,?,?,?,?,?,?,?,?,?,?)`;

    const executionSet: capSQLiteSet[] = [];

    forEach(expenseTemplates, (e) => {
      const values = [
        e?.id,
        e?.templateName,
        e?.expenseTemplateIconId,
        e?.isNameEnabled,
        e?.isAmountEnabled,
        e?.isDateEnabled,
        e?.isExpenseTypeEnabled,
        e?.isVatEnabled,
        e?.isPhotoEnabled,
        e?.createdDate,
        e?.userId,
      ];

     executionSet.push({
        statement,
        values,
      });
    });


    return this.sqliteDbConnection.executeSet(executionSet, true);
  }
```

**Comment by Sampath-Lokuge** [comment]
Hi @tobiasmuecksch 

Ok sure. All are working fine now. Thanks a lot for the support.
