### ISSUE TITLE
Bug: CreateSyncTable: No last_modified column in tables

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capacitor-community/sqlite#281]
Hi,

```
error.service.ts:21 Error: Uncaught (in promise): Error: CreateSyncTable: No last_modified column in tables
Error: CreateSyncTable: No last_modified column in tables
    at Object.cap.fromNative (VM3:414:32)
    at <anonymous>:1:18
    at resolvePromise (zone.js:1255:1)
    at resolvePromise (zone.js:1209:1)
    at zone.js:1162:1
    at asyncGeneratorStep (asyncToGenerator.js:11:1)
    at _throw (asyncToGenerator.js:29:1)
    at ZoneDelegate.invoke (zone.js:400:1)
    at Object.onInvoke (core.mjs:25826:1)
    at ZoneDelegate.invoke (zone.js:399:1)
    at Zone.run (zone.js:160:1)
    at zone.js:1318:1
```

I use the latest version of this plugin. i.e. ` "@capacitor-community/sqlite": "3.5.1-2",`

I do not need to have `last_modified` column on all the tables. e.g. No need it for Master tables. So how can I avoid it? Now it shows the above error. Thanks!

Code

```
 async createExpenseTemplateIcons(
    expenseTemplateIcons: ExpenseTemplateIconModel[]
  ): Promise<void> {
    const query = `
            CREATE TABLE IF NOT EXISTS ExpenseTemplateIcons (
              ExpenseTemplateIconId TEXT PRIMARY KEY NOT NULL,
              YellowIcon BLOB NOT NULL,
              BlackIcon BLOB NOT NULL,
              CreatedDate INTEGER NOT NULL
             );                             
             `;

    await this.sqliteDbConnection.execute(query);

}


```

**Comment by Sampath-Lokuge** [comment]
I would like to accept this change due to maintain a consistent API across the tables. i.e. I have done that change now on my tables.
