### ISSUE TITLE
Unable to query database; getting `caught (in promise) Error: both async and sync fetching of the wasm failed `

### ISSUE THREAD

**Issue by thatsbrandon** [capacitor-community/sqlite#413]
**Describe the bug**
App is unable to query database due to `caught (in promise) Error: both async and sync fetching of the wasm failed` error occurring in the console. Even with `jeep-sqlite`. All of this is within a SolidJS app

```ts
import { Capacitor } from "@capacitor/core";
import { CapacitorSQLite, SQLiteConnection } from "@capacitor-community/sqlite";

export const platform = Capacitor.getPlatform();
export const sqlite: SQLiteConnection = new SQLiteConnection(CapacitorSQLite);
```

```ts
// index.tsx
import { render } from 'solid-js/web';
import Root from "@/Root";

import { JeepSqlite } from "jeep-sqlite/dist/components/jeep-sqlite";
import { platform, sqlite } from './App';

customElements.define('jeep-sqlite', JeepSqlite);

window.addEventListener('DOMContentLoaded', async () => {
  try {
    if (platform === 'web') {
      const jeepEl = document.createElement("jeep-sqlite");
      document.body.appendChild(jeepEl);
      await customElements.whenDefined('jeep-sqlite');
      await sqlite.initWebStore();
    }
    // @ts-ignore
    render(() => (<Root />), document.getElementById('root'));  
  } catch (err) {
    console.log(`Error: ${err}`);
    throw new Error(`Error: ${err}`) 
  }
})
```

```ts
const openConnection = async (dbName: string, encrypted: boolean): Promise<SQLiteDBConnection> => {
	let db: SQLiteDBConnection;
	try {
		const retCC = (await sqlite.checkConnectionsConsistency()).result;
		let isConn = (await sqlite.isConnection(dbName, false)).result;
		if (retCC && !isConn) {
			db = await sqlite.retrieveConnection(dbName, false);
		} else {
			db = await sqlite.createConnection(dbName, encrypted, "", 1, false);
		}
		await db.open();
		return db;
	} catch (err) {
		return Promise.reject(err);
	}
}

export const testConnection = async () => {
	let q = `CREATE TABLE IF NOT EXISTS users (
		name TEXT,
		size TEXT,
	)`;
	let db = await openConnection("Test", false);
	await db.query(q)
}
```
When trying to run testConnection() that is when the error `caught (in promise) Error: both async and sync fetching of the wasm failed` is thrown.

Am I setting things up wrong, the docs can be a bit confusing at times.

**Expected behavior**
Query to be executed

**Desktop (please complete the following information):**

- OS: Fedora Workstation 37
- Browser: Brave

**Additional context**
Not sure if I setup the following package up correctly, can someone shed some light on what is going on?

**Comment by thatsbrandon** [comment]
wasm.js:39 Uncaught (in promise) Error: both async and sync fetching of the wasm failed
    at Module.onAbort (sql-wasm.js:39:16)
    at E (sql-wasm.js:101:94)
    at ab (sql-wasm.js:102:139)
    at sql-wasm.js:103:238

ERROR I keep getting

This package has some of the worst docs I've ever laid my eyes on.

**Comment by jepiqueau** [comment]
@thatsbrandon can you share your package.json file and the name of the files in your assets directory

**Comment by jepiqueau** [comment]
@thatsbrandon Did you look at [capacitor-solid-sqlite](https://github.com/jepiqueau/capacitor-solid-sqlite).

**Comment by thatsbrandon** [comment]
@jepiqueau Yes I'll link you my package.json when I get back home & my assets directory, I ported over a chrome extension over to capacitor & maybe the file structure is the problem

**Comment by thatsbrandon** [comment]
@jepiqueau 

Repo fs
`app/` is my main folder for the application, could this be an issue to?
```
android/
app/
.babelrc
capacitor.config.ts
dist/
fonts/
.git/
.gitignore
index.html
node_modules/
package.json
package-lock.json
src/
tsconfig.json
types.d.ts
vite.config.ts
yarn-error.log
yarn.lock
```
package.json
```
{
  "name": "oc-extension",
  "version": "1.0.0",
  "main": "index.tsx",
  "license": "MIT",
  "scripts": {
    "start": "vite",
    "build": "vite build && yarn run copysqlwasm",
    "preview": "vite preview",
    "copysqlwasm": "copyfiles -u 3 node_modules/sql.js/dist/sql-wasm.wasm dist/assets"
  },
  "dependencies": {
    "@capacitor-community/sqlite": "^4.8.0-1",
    "@motionone/solid": "^10.16.0",
    "@solidjs/router": "^0.8.2",
    "utils": "5.7.0",
    "motion": "^10.15.5",
    "solid-js": "^1.7.5",
    "solid-styled-components": "^0.28.5",
    "remotion": "1.10.0"
  },
  "devDependencies": {
    "@capacitor/android": "^5.0.3",
    "@capacitor/cli": "^5.0.3",
    "@capacitor/core": "^5.0.3",
    "@types/node": "^20.1.3",
    "typescript": "^5.0.4",
    "vite": "^4.3.5",
    "vite-plugin-solid": "^2.7.0"
  }
}
```

file structure of `dist/assets`
```
core-js-504692ca.js  
dom-442bff65.js  
rel-d22a4167.svg  
index-e07837b4.js  
modal-close-c1ac7a4d.svg  
sql-wasm.wasm*  
temp_logo-c476308c.svg  
eb-ce6d0130.js  
zap-113cd8f0.svg
```

**Comment by jepiqueau** [comment]
@thatsbrandon i reproduce the issue it doesn't find the sql-wasm.wasm in the assets directory. So it seems that it is due to vite so i will have to look d'expérience at the new vite release and where the port:3000 is setup. Sorry for the désagrément mzy be you could try to define à wasmpath in the jeep-sqlite property. I will not be able to work more today

**Comment by thatsbrandon** [comment]
@thatsbrandon Yes I actually just traced that right now, looking in chrome dev tools, under sources & in the assets folder, `sql-wasm.wasm` wasn't copied even though I'm copying it.

I'll try to define a wasmpath in jeep-sqlite even though I'm not sure how to do so exactly

**Comment by jepiqueau** [comment]
@thatsbrandon well i did a new test you must do npm run serve and not npm start and it will work i put back the new release of capacitor-solid-sqlite even if i did not find yet the way to handle the css which have also change

**Comment by thatsbrandon** [comment]
@jepiqueau I don't have a `serve` command for npm to run what command do I give it?
```json
"scripts": {
    "start": "vite",
    "build": "vite build && yarn run copysqlwasm",
    "preview": "vite preview",
    "copysqlwasm": "copyfiles -u 3 node_modules/sql.js/dist/sql-wasm.wasm dist/assets"
  }
```
Here are my scripts

**Comment by jepiqueau** [comment]
@thatsbrandon 
```
  "scripts": {
    "start": "vite",
    "dev": "vite",
    "build": "vite build && npm run copysqlwasm",
    "serve": "npm run build && vite preview",
    "copysqlwasm": "copyfiles -u 3 node_modules/sql.js/dist/sql-wasm.wasm dist/assets"
  },

```

**Comment by jepiqueau** [comment]
@thatsbrandon  `vite start` has a public base path to`/` 
so the way to make it working for `npm start`will be to define a different public base
so finally the scripts in package.json should be
```
  "scripts": {
    "start": "npm run copysqlwasm && vite --base /public",
    "dev": "npm run copysqlwasm && vite --base /public",
    "build": "vite build --outDir public && npm run copysqlwasm ",
    "serve": "npm run build && vite preview --outDir public",
    "copysqlwasm": "copyfiles -u 3 node_modules/sql.js/dist/sql-wasm.wasm public/assets"
  },

```
and you must modify the capacitor-config.ts as follows:
```
...
const config: CapacitorConfig = {
  appId: 'com.jeep.app.solidjs',
  appName: 'capacitor-solid-sqlite',
  webDir: 'public',
...
};
...
hope this solve the issue if yes please close it

**Comment by jepiqueau** [comment]
@thatsbrandon i published  [capacitor-solid-sqlite](https://github.com/jepiqueau/capacitor-solid-sqlite) version 1.0.1 which is implementing all what i said above and use tailwind.css. So n ow everything is working as before

**Comment by thatsbrandon** [comment]
@jepiqueau Nice! Haven't been able to test yet, was working on a Rust repo today, will try within the next couple hours

**Comment by thatsbrandon** [comment]
@jepiqueau Nice! Everything works as expected! Thanks so much for your help & guidance. Closing issue
