### ISSUE TITLE
RequestPermissions exception

### ISSUE THREAD

**Issue by eugenezhornyak** [capacitor-community/sqlite#51]
**Describe the bug**
I try to create database using sqlite service from https://github.com/jepiqueau/angular-sqlite-app-starter

I have next code:
app.component.ts:
``` 
async ngAfterViewInit() {
    await this.databaseInitService.initializeDatabase();
 }
```
database.initialization.service.ts
```
public async initializeDatabase(): Promise<any> {
    return this.sqliteService.initializePlugin().then(initResult => {
      console.log('Initialize result:' + initResult);
      this.sqliteService.getEcho('Hello!');
      this.sqliteService.openDB(this.dbName).then(openDBResult => {
        console.log('Database open result:' + JSON.stringify(openDBResult));
        this.sqliteService.execute(this.initCmd);
        this.sqliteService.execute(this.seedData);
      });
    });
  }
```
But after launching my app I have next exception:

/io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.ionic.starter, PID: 11955
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=9538, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {io.ionic.starter/io.ionic.starter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.getcapacitor.PluginCall.resolve()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.getcapacitor.PluginCall.resolve()' on a null object reference
        at com.getcapacitor.community.database.sqlite.CapacitorSQLite.handleRequestPermissionsResult(CapacitorSQLite.java:527)
        at com.getcapacitor.Bridge.onRequestPermissionsResult(Bridge.java:747)
        at com.getcapacitor.BridgeActivity.onRequestPermissionsResult(BridgeActivity.java:206)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8264)
        at android.app.Activity.dispatchActivityResult(Activity.java:8114)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 

**To Reproduce**

I have created a repository with code where you can reproduce the bug:
https://github.com/eugenezhornyak/ionic-sqlite-example

1. Run project
2. App crashes

**Expected behavior**
SQLite database initialized and my repository class can execute queries to it.

**Desktop:**

Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Smartphone (please complete the following information):**

Name: Pixel_2_API_29
CPU/ABI: Google Play Intel Atom (x86)
Target: google_apis_playstore [Google Play] (API level 29)
Skin: pixel_2
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.device.name: pixel_2
hw.lcd.width: 1080
image.androidVersion.api: 29
tag.id: google_apis_playstore
hw.mainKeys: no
avd.ini.displayname: Pixel 2 API 29
hw.gpu.mode: auto
PlayStore.enabled: true
fastboot.forceColdBoot: no
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 1920
skin.dynamic: yes
hw.device.manufacturer: Google
image.sysdir.1: system-images\android-29\google_apis_playstore\x86\
showDeviceFrame: yes
AvdId: Pixel_2_API_29
hw.lcd.density: 420
hw.arc: false
hw.device.hash2: MD5:55acbc835978f326788ed66a5cd4c9a7
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
tag.display: Google Play
runtime.network.latency: none
disk.dataPartition.size: 6442450944
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

**Comment by jepiqueau** [comment]
@eugenezhornyak
First thanks for using the plugin, i spent my afternoon to try understanding what is wrong. In fact the main reason is that the way you want to work with the plugin is questionable. In fact, the `sqliteService` instance use in `DatabaseInitializationService` and the one `ProductsRepositoryService` is not the same meaning that the 
```
res = mDb.querySQL(statement, new ArrayList<String>());
``` in the CapacitorSQLite.java file  the mDb is null as the open method has not been called for that instance.

The way you make your `readAll()` method in `ProductsRepositoryService` is wrong. It should be 
```
  async readAll(): Promise<Product[]> {
    /*
    return this.executeIfDbExist(this.selectAllCommand).then(result => {
      console.log('Read products result:' + JSON.stringify(result));
      return result;
    });
    */ 
    return await this.sqliteService.query(this.selectAllCommand);
  }

```
YOU DO NOT REALLY NEED TO EXECUTE executeIfDbExist
as when you run the database.initialization.service.initializeDatabase()
if it return false you do not execute in Home page the refreshData()
if you still do it, it will slow down the app for nothing

I didn't find the way to make the SQLiteService a singleton through the app. 

From Angular doc
```
Providing a singleton service
There are two ways to make a service a singleton in Angular:

 - Set the providedIn property of the @Injectable() to "root".
 - Include the service in the AppModule or in a module that is only imported by the AppModule
```
I have tried both but i did not find the way to make it working.

Look at `https://github.com/jepiqueau/angular-sqlite-app-starter` this one works, and build your application along that.
If you find the way to make the SQLiteService a singleton, i will be interested in

**Comment by jepiqueau** [comment]
@eugenezhornyak i have found the solution. I have to update first the android plugin to implement a listener for granted permissions and after this i will share the app.

**Comment by jepiqueau** [comment]
@eugenezhornyak have a look at `https://github.com/jepiqueau/test-sqlite-issue51`
You cannot instantiate `DatabaseInitializationService` in the `ngAfterViewInit` lifecycle event on the `app.component` as the router bring you straight forward in the `Home` page. Hope this will help.

**Comment by eugenezhornyak** [comment]
@jepiqueau Thank you for attention paid! Your solution is very helpful. My problem solved

**Comment by jepiqueau** [comment]
@eugenezhornyak Happy that everything works fine. i close the issue
